[package]
name = "anion"
version = "0.1.0"
authors = ["Yang Chen <matthiasychen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.4.0"
rand = "0.7.3"